spring:
  data:
    redis:
      host: localhost
      port: 6379
  config:
    activate:
      on-profile: local
  sql:
    init:
      platform: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/cocktaildakk_database?autoReconnect=true&setTimezone=Asia/Seoul&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # create, update, create-drop, none ?? ??? ????.
    # create: ????? ?? ? ?? ??
    # update: ??? ??? ??
    # create-drop: create? ??? ?? ??? ??? DROP
    # none: ???? ??
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # DDl ?? ? ?????? ??? ?? ????
    generate-ddl: false
    # ???? ??? ???? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

